apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vanilla-ui
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'vanilla-ui:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/undefspi/vanilla-ui.git'
    type: Git
  strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'nodejs:latest'
          namespace: openshift
      type: Source
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 38ccfe1c7270109f
      type: Generic
    - github:
        secret: 259d9ff7a282e8ff
      type: GitHub
status:
  lastVersion: 0
