apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "vanilla-test-pipeline", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    name: vanilla-pipeline
  name: vanilla-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        try {
            timeout(time: 20, unit: 'MINUTES') {
              node('nodejs') {
                  stage('build') {
                    openshiftBuild(buildConfig: 'vanilla-ui', showBuildLogs: 'true')
                  }
                  stage('deploy') {
                    openshiftDeploy(deploymentConfig: 'vanilla-ui')
                  }
                }
            }
        } catch (err) {
            echo "in catch block"
            echo "Caught: ${err}"
            currentBuild.result = 'FAILURE'
            throw err
        }          
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic