apiVersion: v1
kind: Service
metadata:
  labels:
    app: vanilla-ui
  name: vanilla-ui
  namespace: vanilla-ui-pipeline   
spec:
  selector:       
    deploymentconfig: vanilla-ui
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 3000 